-- ============================================
-- Service Exchange (SE) — Supabase (PostgreSQL) Schema
-- Durum: 🔴 HENÜZ UYGULANMADI — Taslak / Referans Dosyası
-- Versiyon: V2
-- Son Güncelleme: 2026-04-10
-- ============================================
--
-- ⚠️  BU DOSYA DOĞRUDAN ÇALIŞTIRMAK İÇİN DEĞİL,
--     UYGULAMA SIRASINDA AŞAMA AŞAMA KULLANMAK İÇİNDİR.
--
-- Uygulama Sırası:
--   Aşama 1 → Extensions (postgis, pg_cron)
--   Aşama 2 → Tablolar (profiles, categories, services, service_requests, reviews, credit_transactions)
--   Aşama 3 → Trigger'lar (yeni üye, review güncelleme, avg_rating)
--   Aşama 4 → RPC Fonksiyonları (transfer_credits, check_credits)
--   Aşama 5 → pg_cron Job (48 saat expire)
--   Aşama 6 → RLS Poliçeleri (ayrı dosyada yazılacak)
--
-- ============================================


-- ============================================
-- AŞAMA 1 — EKLENTİLER (EXTENSIONS)
-- ============================================
-- 📌 HATIRLATMA: Supabase Dashboard > Database > Extensions ekranından
--    aşağıdaki eklentilerin UI üzerinden de aktif edildiğini doğrula.
--    SQL ile çalıştırmak yeterli ama görsel doğrulama önerilir.

-- Harita ve Mesafe hesaplamaları için PostGIS eklentisini aktif et
CREATE EXTENSION IF NOT EXISTS postgis;

-- 48 saatlik otomatik expire için pg_cron eklentisi
-- ⚠️  UYARI: pg_cron yalnızca Supabase Pro plan ve üzerinde
--     ya da self-hosted Supabase'de kullanılabilir!
--     Free tier'da bu extension çalışmaz.
CREATE EXTENSION IF NOT EXISTS pg_cron;


-- ============================================
-- AŞAMA 2 — TABLOLAR
-- ============================================

-- --------------------------------------------
-- 2.1) PROFILES
-- --------------------------------------------
-- 📌 HATIRLATMA: Bu tablo Supabase'in kendi 'auth.users' tablosuna bağlıdır.
--    Supabase Auth aktif olmalı ve Email OTP açık olmalıdır.
--    (Dashboard > Authentication > Providers > Email > "Enable Email OTP" ✅)
--
-- 📌 avatar_url: Supabase Storage'a yüklenen dosyanın public URL'sidir.
--    Bucket adı örnek: 'avatars' — public erişime açık olmalı.
--    URL formatı: https://<project>.supabase.co/storage/v1/object/public/avatars/<filename>
--
-- 📌 avg_rating: Manuel güncellenmez! Aşama 3'teki trigger otomatik günceller.
--    credits >= 0 constraint'i sayesinde bakiye asla 0'ın altına düşemez.
--
-- 📌 ROL SİSTEMİ (4 katmanlı):
--    user        → Normal kullanıcı. Servis ekler/alır, review yazar.
--    moderator   → İçerik onayı: servis ve review'ları onayla/reddet.
--                  Kullanıcıları listeler. Kredi/admin yetkisi YOK.
--    admin       → Moderatör yetkileri + kategori yönetimi
--                  + kullanıcı kredi yönetimi + moderatör atama.
--    superadmin  → Tam yetki: admin atama/kaldırma + sistem ayarları.
--                  Veritabanında yalnızca 1 adet olması önerilir.

CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    bio TEXT,
    avatar_url TEXT,                          -- Supabase Storage public URL
    city TEXT,
    location geography(POINT),               -- PostGIS: ST_MakePoint(longitude, latitude)
    credits INTEGER NOT NULL DEFAULT 1 CHECK (credits >= 0),
    avg_rating NUMERIC(3,2) DEFAULT 0.00,    -- Trigger tarafından otomatik güncellenir
    role TEXT CHECK (role IN ('user', 'moderator', 'admin', 'superadmin')) DEFAULT 'user',
    total_services_given INTEGER DEFAULT 0,
    total_services_received INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------
-- 2.2) CATEGORIES
-- --------------------------------------------
-- 📌 HATIRLATMA: Kategoriler yalnızca admin panelinden yönetilir.
--    RLS'de INSERT/UPDATE/DELETE sadece role IN ('admin', 'superadmin') olanlara açılacak.
--    parent_id = NULL olan kategoriler kök (root) kategorilerdir.
--    İlk seed verisi (8 kök kategori) ayrı bir seed.sql dosyasında olacak.

CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    icon TEXT,                               -- Material Icon adı (örn: 'school', 'computer')
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------
-- 2.3) SERVICES
-- --------------------------------------------
-- 📌 HATIRLATMA: Yeni servis eklenince status otomatik 'pending_approval' olur.
--    moderator, admin veya superadmin onaylamadan 'active' olmaz.
--    Flutter'da onay için UI yok; bunun için Admin Web Panel (Faz 5) kullanılacak.
--
-- 📌 rejection_reason: Admin reddedince bu alana sebep yazar.
--    Flutter'da kullanıcıya "Servisiniz şu sebepten reddedildi: ..." şeklinde gösterilir.
--
-- 📌 location: Sadece location_type = 'in_person' veya 'both' ise doldurulur.
--    online servisler için NULL bırakılabilir.

CREATE TABLE public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE RESTRICT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    credit_cost INTEGER NOT NULL DEFAULT 1 CHECK (credit_cost >= 1),
    location_type TEXT CHECK (location_type IN ('online', 'in_person', 'both')) DEFAULT 'both',
    city TEXT,
    location geography(POINT),               -- Yalnızca yüz yüze servisler için
    status TEXT CHECK (status IN ('pending_approval', 'active', 'inactive', 'rejected')) DEFAULT 'pending_approval',
    rejection_reason TEXT,                   -- Admin tarafından doldurulur
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------
-- 2.4) SERVICE REQUESTS
-- --------------------------------------------
-- 📌 HATIRLATMA: Flutter, INSERT sırasında expires_at değerini manuel set etmelidir:
--    expires_at = DateTime.now().toUtc().add(Duration(hours: 48))
--    Bu olmadan pg_cron job'u expire edemez!
--
-- 📌 credits_amount: INSERT anında servisin o anki credit_cost'u kopyalanır (snapshot).
--    Böylece servis sahibi fiyatı değiştirse bile eski talepler etkilenmez.
--
-- 📌 Kredi, yalnızca status='completed' olduğunda transfer edilir.
--    Transfer işlemi transfer_credits() RPC'si ile yapılır (Aşama 4).
--    Flutter, tamamlama butonuna basıldığında önce status'u 'completed' yapar,
--    ardından transfer_credits() RPC'sini çağırır.

CREATE TABLE public.service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT REFERENCES public.services(id) ON DELETE CASCADE NOT NULL,
    requester_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    provider_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT CHECK (status IN ('pending', 'accepted', 'rejected', 'in_progress', 'completed', 'cancelled', 'expired')) DEFAULT 'pending',
    message TEXT,
    credits_amount INTEGER NOT NULL,          -- INSERT anında credit_cost snapshot'lanır
    expires_at TIMESTAMP WITH TIME ZONE,      -- Flutter: NOW() + 48 saat olarak set et!
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------
-- 2.5) REVIEWS
-- --------------------------------------------
-- 📌 HATIRLATMA: Review yalnızca status='completed' olan talepler için yazılabilir.
--    Bu kontrol RLS poliçesinde zorlanacak.
--
-- 📌 UNIQUE(service_request_id, review_type) kısıtı sayesinde her talep için
--    her yönde (alıcı→verici, verici→alıcı) yalnızca 1 review yazılabilir.
--
-- 📌 Review düzenlenince Aşama 3'teki trigger otomatik olarak
--    status'u 'pending_approval'a geri çeker.

CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT REFERENCES public.service_requests(id) ON DELETE CASCADE NOT NULL,
    reviewer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    reviewee_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    review_type TEXT CHECK (review_type IN ('requester_to_provider', 'provider_to_requester')) NOT NULL,
    rating SMALLINT CHECK (rating BETWEEN 1 AND 5) NOT NULL,
    comment TEXT,
    status TEXT CHECK (status IN ('pending_approval', 'approved', 'rejected')) DEFAULT 'pending_approval',
    rejection_reason TEXT,                   -- Admin tarafından doldurulur
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE (service_request_id, review_type)
);

-- --------------------------------------------
-- 2.6) CREDIT TRANSACTIONS
-- --------------------------------------------
-- 📌 HATIRLATMA: Bu tabloya doğrudan INSERT YAPILMAZ.
--    Tüm kayıtlar yalnızca trigger ve RPC fonksiyonları tarafından oluşturulur.
--    RLS'de: SELECT sadece kendi kayıtları, INSERT/UPDATE/DELETE tamamen kapalı.
--
-- 📌 amount: Kazanılan krediler POZİTİF (+), harcanan krediler NEGATİF (-) olarak kaydedilir.
--    balance_after: işlem sonrası kullanıcının toplam kredisi.

CREATE TABLE public.credit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    amount INTEGER NOT NULL,                  -- Pozitif: kazanılan, Negatif: harcanan
    type TEXT CHECK (type IN ('signup_bonus', 'service_given', 'service_received', 'admin_adjustment')) NOT NULL,
    service_request_id BIGINT REFERENCES public.service_requests(id) ON DELETE SET NULL,
    balance_after INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ============================================
-- AŞAMA 3 — TRIGGER'LAR (DB FUNCTIONS)
-- ============================================

-- --------------------------------------------
-- 3.1) YENİ ÜYE KAYDI → PROFİL + KREDİ
-- --------------------------------------------
-- 📌 HATIRLATMA: Bu trigger, Supabase Auth üzerinden yeni kullanıcı oluşturulduğunda
--    otomatik olarak tetiklenir. Flutter'da manuel profiles INSERT yapma!
--    Kayıt sırasında raw_user_meta_data içinde first_name ve last_name gönderilmelidir:
--    await supabase.auth.signUp(email: ..., password: ...,
--      data: {'first_name': 'Ali', 'last_name': 'Veli'})

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name, credits)
  VALUES (new.id, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', 1);

  INSERT INTO public.credit_transactions (user_id, amount, type, balance_after, description)
  VALUES (new.id, 1, 'signup_bonus', 1, 'Welcome bonus!');

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- --------------------------------------------
-- 3.2) REVIEW GÜNCELLENİNCE TEKRAR ONAYA DÜŞÜR
-- --------------------------------------------
-- 📌 HATIRLATMA: Flutter'da UPDATE yaparken status alanına dokunma.
--    Bu trigger otomatik olarak status='pending_approval' yapacak.
--    rejection_reason da otomatik temizlenir.

CREATE OR REPLACE FUNCTION public.handle_review_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.rating IS DISTINCT FROM NEW.rating OR OLD.comment IS DISTINCT FROM NEW.comment THEN
    NEW.status := 'pending_approval';
    NEW.rejection_reason := NULL;
    NEW.updated_at := NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_review_update
  BEFORE UPDATE ON public.reviews
  FOR EACH ROW EXECUTE PROCEDURE public.handle_review_update();

-- --------------------------------------------
-- 3.3) REVIEW ONAYLANINCA avg_rating GÜNCELLE
-- --------------------------------------------
-- 📌 HATIRLATMA: Bu trigger otomatik çalışır, Flutter tarafında avg_rating
--    hesaplamaya ya da güncellemeye GEREK YOK.
--    Yalnızca status='approved' olan review'ların ortalaması hesaplanır.

CREATE OR REPLACE FUNCTION public.update_avg_rating()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'approved' OR OLD.status = 'approved' THEN
    UPDATE public.profiles
    SET avg_rating = (
      SELECT COALESCE(AVG(rating), 0)
      FROM public.reviews
      WHERE reviewee_id = NEW.reviewee_id AND status = 'approved'
    )
    WHERE id = NEW.reviewee_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_review_status_change
  AFTER INSERT OR UPDATE OF status ON public.reviews
  FOR EACH ROW EXECUTE PROCEDURE public.update_avg_rating();


-- ============================================
-- AŞAMA 4 — RPC FONKSİYONLARI
-- ============================================

-- --------------------------------------------
-- 4.1) transfer_credits — Kredi Transferi
-- --------------------------------------------
-- 📌 HATIRLATMA: Bu fonksiyon yalnızca status='completed' olan talepler için çalışır.
--    Flutter'da kullanım sırası:
--      1. service_request'i 'completed' yap
--      2. transfer_credits RPC'sini çağır:
--         await supabase.rpc('transfer_credits', params: {'p_service_request_id': requestId});
--
-- ⚠️  UYARI: Bu fonksiyonu doğrudan tarayıcıdan veya Postman'den çağırmayın.
--    SECURITY DEFINER ile çalışır, yani DB sahibi yetkisiyle execute eder.
--    RLS poliçesinde bu fonksiyona kimin erişebileceği kısıtlanacak.

CREATE OR REPLACE FUNCTION public.transfer_credits(p_service_request_id BIGINT)
RETURNS VOID AS $$
DECLARE
  v_requester_id UUID;
  v_provider_id  UUID;
  v_credits      INTEGER;
  v_requester_balance INTEGER;
  v_provider_balance  INTEGER;
BEGIN
  SELECT requester_id, provider_id, credits_amount
  INTO v_requester_id, v_provider_id, v_credits
  FROM public.service_requests
  WHERE id = p_service_request_id AND status = 'completed';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Service request not found or not completed (id: %)', p_service_request_id;
  END IF;

  -- Bakiye kontrolü (kredi 0'ın altına düşemez)
  SELECT credits INTO v_requester_balance FROM public.profiles WHERE id = v_requester_id FOR UPDATE;
  IF v_requester_balance < v_credits THEN
    RAISE EXCEPTION 'Insufficient credits. Required: %, Available: %', v_credits, v_requester_balance;
  END IF;

  -- Alıcıdan düş
  UPDATE public.profiles SET credits = credits - v_credits WHERE id = v_requester_id;
  SELECT credits INTO v_requester_balance FROM public.profiles WHERE id = v_requester_id;
  INSERT INTO public.credit_transactions (user_id, amount, type, service_request_id, balance_after, description)
  VALUES (v_requester_id, -v_credits, 'service_received', p_service_request_id, v_requester_balance, 'Service payment');

  -- Vericiye ekle
  UPDATE public.profiles SET credits = credits + v_credits WHERE id = v_provider_id;
  SELECT credits INTO v_provider_balance FROM public.profiles WHERE id = v_provider_id;
  INSERT INTO public.credit_transactions (user_id, amount, type, service_request_id, balance_after, description)
  VALUES (v_provider_id, v_credits, 'service_given', p_service_request_id, v_provider_balance, 'Service earning');

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- --------------------------------------------
-- 4.2) check_credits — Kredi Yeterlilik Kontrolü
-- --------------------------------------------
-- 📌 HATIRLATMA: Flutter, service_request oluşturmadan ÖNCE bu fonksiyonu çağırmalı.
--    Yetersiz bakiyede kullanıcıya hata gösterilmeli, INSERT yapılmamalıdır.
--    Kullanım:
--      final result = await supabase.rpc('check_credits',
--        params: {'p_user_id': userId, 'p_required': creditCost});
--      if (result == false) { // Hata göster }

CREATE OR REPLACE FUNCTION public.check_credits(p_user_id UUID, p_required INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
  v_balance INTEGER;
BEGIN
  SELECT credits INTO v_balance FROM public.profiles WHERE id = p_user_id;
  RETURN v_balance >= p_required;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ============================================
-- AŞAMA 5 — pg_cron: 48 SAAT OTOMATİK EXPIRE
-- ============================================
-- 📌 ÖN KOŞULLAR (önce bunları yap!):
--    1. Supabase Dashboard > Database > Extensions > pg_cron'u aktif et
--    2. Free tier kullanıyorsan bu adımı atlayabilirsin;
--       bunun yerine Supabase Edge Function + Scheduled Trigger kullan.
--
-- 📌 Flutter'da SERVICE REQUEST INSERT yaparken:
--    'expires_at': DateTime.now().toUtc().add(Duration(hours: 48)).toIso8601String()
--    Bunu set etmezsen aşağıdaki job çalışmaz!
--
-- ⚠️  UYARI: Bu SELECT'i yalnızca pg_cron aktifken çalıştır.
--    Aksi takdirde 'function cron.schedule does not exist' hatası alırsın.

SELECT cron.schedule(
  'expire-pending-service-requests',   -- job adı (benzersiz olmalı)
  '*/10 * * * *',                      -- her 10 dakikada bir çalışır
  $$
    UPDATE public.service_requests
    SET status = 'expired', updated_at = NOW()
    WHERE status = 'pending'
      AND expires_at IS NOT NULL
      AND expires_at < NOW();
  $$
);


-- ============================================
-- AŞAMA 6 — RLS (HENÜZ YAZILMADI)
-- ============================================
-- 📌 RLS poliçeleri ayrı bir dosyada (RLS_Policies.sql) yazılacak.
--    Şema kurulumu tamamlanınca Faz 2'de uygulanacak.
--
-- Planlanan kısıtlamalar (4 rol: user / moderator / admin / superadmin):
--   profiles        → Herkes SELECT | Sadece kendisi UPDATE | admin+superadmin tümünü görür
--   categories      → Herkes SELECT | Sadece admin & superadmin INSERT/UPDATE/DELETE
--   services        → Herkes SELECT (active) | Sadece sahibi yazar | mod/admin/superadmin status günceller
--   service_requests→ Sadece requester/provider okur & yazar | mod/admin/superadmin listeler (salt okunur)
--   reviews         → Onaylananlar herkese SELECT | Sadece reviewer yazar | mod/admin/superadmin status günceller
--   credit_trans.   → Sadece kendisi SELECT | Kimse doğrudan yazamaz | admin+superadmin listeler
--   rol atama       → moderator rolunu admin & superadmin verir; admin rolünü yalnızca superadmin verir
